const DEFAULTS={focus:25,short:5,long:15,cycle:4,dailyGoal:240,autoBreak:false,autoFocus:false,soundEnabled:true,volume:.7,soundUrl:"",imageUrl:"",videoUrl:"",theme:"dark"};
const state={settings:{...DEFAULTS,...JSON.parse(localStorage.getItem("focusSettings")||"{}")},mode:"focus",session:1,running:false,remaining:0,endAt:null,startedAt:null,credited:0,stats:null,media:null,audio:null};
const $=id=>document.getElementById(id);
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function dayDiff(a,b){return Math.round((new Date(b)-new Date(a))/86400000)}
function loadStats(){const s=JSON.parse(localStorage.getItem("focusStats")||"null"); if(!s||s.day!==today()){state.stats={day:today(),focusSeconds:0,sessions:0,streak:s?.streak||0,lastDate:s?.lastDate||null};}else state.stats=s;}
function saveStats(){localStorage.setItem("focusStats",JSON.stringify(state.stats))}
function duration(){return ({focus:state.settings.focus,short:state.settings.short,long:state.settings.long}[state.mode])*60}
function resetRemaining(){state.remaining=duration();state.running=false;state.endAt=null;state.startedAt=null;state.credited=0;update()}
function fmt(sec){sec=Math.max(0,Math.ceil(sec));return `${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`}
function fmtLong(sec){const m=Math.floor(sec/60);if(m<60)return `${m}m`;return `${Math.floor(m/60)}h ${m%60}m`}
function touchStreak(){const t=today();if(state.stats.lastDate===t)return;if(!state.stats.lastDate)state.stats.streak=1;else{const d=dayDiff(state.stats.lastDate,t);state.stats.streak=d===1?state.stats.streak+1:1}state.stats.lastDate=t;saveStats()}
function creditFocus(seconds){if(seconds<=0)return;state.stats.focusSeconds+=seconds;state.credited+=seconds;if(seconds>=1)touchStreak();saveStats()}
function update(){
  $("timer").textContent=fmt(state.remaining);
  $("mode").textContent=state.mode==="focus"?"FOCUS":state.mode==="short"?"SHORT BREAK":"LONG BREAK";
  $("session").textContent=`SESSION ${state.session} / ${state.settings.cycle}`;
  $("start").textContent=state.running?"Pause":"Start";
  const total=duration();$("timerProgress").style.width=`${Math.min(100,Math.max(0,(total-state.remaining)/total*100))}%`;
  $("focusTime").textContent=fmtLong(state.stats.focusSeconds);
  $("sessions").textContent=state.stats.sessions;
  $("streak").textContent=`${state.stats.streak} 🔥`;
  $("goalText").textContent=`${fmtLong(state.stats.focusSeconds)} / ${fmtLong(state.settings.dailyGoal*60)}`;
  $("goalProgress").style.width=`${Math.min(100,state.stats.focusSeconds/(state.settings.dailyGoal*60)*100)}%`;
}
function start(){if(state.running){pause();return}state.running=true;state.startedAt=Date.now();state.endAt=Date.now()+state.remaining*1000;update()}
function pause(){if(!state.running)return;const now=Date.now();const elapsed=(now-state.startedAt)/1000;const credit=Math.max(0,Math.min(duration(),elapsed)-state.credited);if(state.mode==="focus")creditFocus(credit);state.remaining=Math.max(0,(state.endAt-now)/1000);state.running=false;state.endAt=null;state.startedAt=null;update()}
function playSound(){if(!state.settings.soundEnabled)return;try{if(state.audio){state.audio.pause();state.audio.currentTime=0}if(state.settings.soundUrl){state.audio=new Audio(state.settings.soundUrl);state.audio.volume=Number(state.settings.volume);state.audio.play().catch(()=>{})}else{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C();[0,.18,.36].forEach((t)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.value=660;g.gain.setValueAtTime(0,c.currentTime+t);g.gain.linearRampToValueAtTime(.16*state.settings.volume,c.currentTime+t+.02);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+t+.14);o.connect(g);g.connect(c.destination);o.start(c.currentTime+t);o.stop(c.currentTime+t+.16)})}}catch{}}
function next(manual=false){if(state.mode==="focus"){if(!manual){state.stats.sessions++;saveStats()}if(state.session>=state.settings.cycle){state.mode="long";state.session=1}else state.mode="short"}else if(state.mode==="short"){state.mode="focus";if(!manual)state.session++}else{state.mode="focus"}resetRemaining();playSound();const auto=state.mode==="focus"?state.settings.autoFocus:state.settings.autoBreak;if(auto)start()}
function complete(){if(state.mode==="focus"){const credit=Math.max(0, duration()-state.credited);creditFocus(credit);state.stats.sessions++;saveStats()}state.remaining=0;state.running=false;state.endAt=null;state.startedAt=null;next(false)}
function tick(){if(!state.running)return;const now=Date.now();if(now>=state.endAt){complete();return}const elapsed=Math.max(0,Math.min(duration(),(now-state.startedAt)/1000));if(state.mode==="focus"){const delta=elapsed-state.credited;if(delta>0){creditFocus(delta)}}state.remaining=(state.endAt-now)/1000;update()}
function saveSettings(){state.settings={...state.settings,focus:+$("focus").value,short:+$("short").value,long:+$("long").value,cycle:+$("cycle").value,dailyGoal:+$("dailyGoal").value,autoBreak:$("autoBreak").checked,autoFocus:$("autoFocus").checked,soundEnabled:$("soundEnabled").checked,volume:+$("volume").value,soundUrl:$("soundUrl").value.trim(),imageUrl:$("imageUrl").value.trim(),videoUrl:$("videoUrl").value.trim()};localStorage.setItem("focusSettings",JSON.stringify(state.settings));applyBackground();applyTheme();if(!state.running)resetRemaining()}
function loadSettings(){const s=state.settings;$("focus").value=s.focus;$("short").value=s.short;$("long").value=s.long;$("cycle").value=s.cycle;$("dailyGoal").value=s.dailyGoal;$("autoBreak").checked=s.autoBreak;$("autoFocus").checked=s.autoFocus;$("soundEnabled").checked=s.soundEnabled;$("volume").value=s.volume;$("soundUrl").value=s.soundUrl;$("imageUrl").value=s.imageUrl;$("videoUrl").value=s.videoUrl}
function applyTheme(){document.body.classList.toggle("light",state.settings.theme==="light");$("themeBtn").textContent=state.settings.theme==="light"?"☾":"☀"}
function applyBackground(){const v=$("bgVideo"),b=$("bg");v.hidden=true;v.removeAttribute("src");b.style.background="";b.style.filter="";if(state.settings.videoUrl){v.src=state.settings.videoUrl;v.hidden=false;b.style.display="none"}else{b.style.display="block";if(state.settings.imageUrl){b.style.background=`url("${state.settings.imageUrl}") center/cover no-repeat`;b.style.filter="none"}}}
function saveMedia(){const url=$("mediaUrl").value.trim(),title=$("mediaTitle").value.trim();state.media={url,title};localStorage.setItem("focusMedia",JSON.stringify(state.media));renderMedia()}
function renderMedia(){const m=state.media;if(!m||(!m.url&&!m.title)){$("mediaCard").classList.add("hidden");return}$("mediaCard").classList.remove("hidden");$("mediaTitle").textContent=m.title||"Media";$("mediaSource").textContent=/spotify/i.test(m.url)?"Spotify":/youtu/i.test(m.url)?"YouTube":"Media";const yt=(m.url||"").match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|shorts\/))([^&?/]+)/i);const box=$("mediaThumb");box.innerHTML="♪";if(yt){const img=new Image();img.src=`https://img.youtube.com/vi/${yt[1]}/hqdefault.jpg`;img.onload=()=>{box.innerHTML="";box.appendChild(img)}}}
$("start").onclick=start;$("skip").onclick=()=>{if(state.running)pause();next(true)};$("reset").onclick=()=>$("resetModal").classList.remove("hidden");$("cancelReset").onclick=()=>$("resetModal").classList.add("hidden");$("confirmReset").onclick=()=>{$("resetModal").classList.add("hidden");resetRemaining()};$("settingsBtn").onclick=()=>{$("settings").classList.add("open");$("overlay").classList.add("show");loadSettings()};$("closeSettings").onclick=()=>{$("settings").classList.remove("open");$("overlay").classList.remove("show")};$("overlay").onclick=()=>$("closeSettings").click();$("saveSettings").onclick=()=>{saveSettings();$("closeSettings").click()};$("testSound").onclick=playSound;$("defaultBg").onclick=()=>{$("imageUrl").value="";$("videoUrl").value="";saveSettings()};$("saveMedia").onclick=saveMedia;$("themeBtn").onclick=()=>{state.settings.theme=state.settings.theme==="dark"?"light":"dark";localStorage.setItem("focusSettings",JSON.stringify(state.settings));applyTheme()};
loadStats();state.media=JSON.parse(localStorage.getItem("focusMedia")||"null");applyTheme();applyBackground();renderMedia();resetRemaining();setInterval(tick,250);
